---
- name: Deploy Delivery Application
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "docker-compose.yml"

    - name: Set Docker Context to desktop-linux
      command: docker context use desktop-linux
      ignore_errors: yes

    - name: Run Docker Compose
      command: docker-compose up -d
